config/routes.rb
Moz::Application.routes.draw do

  root :to => "pages#home"

  devise_for :users, :controllers => { :registrations => :registrations }
  devise_for :users, :skip => [:sessions]

  as :user do
    get    'signin' => 'devise/sessions#new', :as => :new_user_session
    post   'signin' => 'devise/sessions#create', :as => :user_session
    delete 'signout' => 'devise/sessions#destroy', :as => :destroy_user_session
  end

  resources :users, :only => [:show, :index]

  resources :users do 

    resources :comments

    resources :articles, :shallow => true do 
      resources :comments 
    end

    resources :events, :shallow => true do 
      resources :comments 
    end

    resources :videos, :shallow => true do 
      resources :comments 
    end

    resources :youtubes, :shallow => true do
      resources :comments
    end

    resources :playlists, :shallow => true do
      resources :ptracks
    end

    resources :albums, :shallow => true do
      resources :comments

      resources :songs do
        resources :comments
      end

    end
  end

  match '/music'               => "pages#music"
  match '/about'               => "pages#about"
  match '/team'                => "pages#team"
  match '/micropost-dashboard' => 'microposts#home',        as: 'song_dashboard'
  match '/song-dashboard'      => 'songs#home',             as: 'song_dashboard'
  match '/gallery-dashboard'   => 'galleries#home',         as: 'gallery_dashboard'
  match '/album-dashboard'     => 'albums#home',            as: 'album_dashboard'
  match '/events-dashboard'    => 'events#home',            as: 'events_dashboard'
  match '/video-dashboard'     => 'videos#home',            as: 'video_dashboard'
  match '/article-dashboard'   => 'articles#home',          as: 'article_dashboard'

end

app/models/article.rb
class Article < ActiveRecord::Base
  belongs_to :user
  has_many :comments, as: :commentable

  attr_accessible :content, :title, :photo
  
  validates :title,
          presence: true,
          length: {
              minimum: 2, maximum: 40,
              :message => "is too short"
          }

  validates :content,
          presence: true,
          length: {
              minimum: 2, maximum: 4000,
              :message => "you have exceded 4000 letters!"
          }
  has_attached_file :photo, :styles => {:small => "150x150#", :medium => "400x400#", :large => "900x900>", :avatar => "60x60#"},
                    :url => "/system/articles/photos/:id/:style/:basename.:extension",
                    :path => ":rails_root/public/system/articles/photos/:id/:style/:basename.:extension"
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  load_and_authorize_resource :only => [:home, :new, :create, :edit, :update, :destroy]
  def home 
    @articles = current_user.articles
  end
  def index
    @user = User.find(params[:user_id])
    @articles = @user.articles
  end

  def show
    @article = Article.find(params[:id])
    @artist = User.find(@article.user_id)

    @commentable = @article
    @comments = @commentable.comments
    @comment = Comment.new
  end
  
  def new
    @user = User.find(params[:user_id])
    @article = @user.articles.build
  end
  
  def create
    @user = User.find(params[:user_id])
    @article = @user.articles.build(params[:article])
    if @article.save
      flash[:notice] = "Successfully created article."
      redirect_to article_dashboard_url
    else
      render :action => 'new'
    end
  end
  
  def edit
    @article = Article.find(params[:id])
    @user = User.find(@article.user_id)
  end
  
  def update
    @article = Article.find(params[:id])
    if @article.update_attributes(params[:article])
      flash[:notice] = "Successfully updated article."
      redirect_to article_dashboard_url
    else
      render :action => 'edit'
    end
  end
  
  def destroy
    @article = Article.find(params[:id])
    @article.destroy
    flash[:notice] = "Successfully destroyed article."
    redirect_to article_dashboard_url
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_edit_form.html.erb
<%= simple_form_for [@article], :html => {:class => 'form-vertical'} do |f| %>
    <%= f.error_notification %>

    <%= f.input :title, :hint => "The title of the article." %>

    <hr>

    <% if @article.photo.file? %>
      <div class="pull-right">
        <h6>Current Image</h6>
        <p><%= image_tag @article.photo.url(:avatar) %></p>
      </div>
    <% end %>
    <%= f.input :photo, :hint => "5MB limit | JPEG/PNG only." %>

    <hr>

    <%= f.input :content, :as => :text, :input_html => {:class => "span6", :rows => 8} %>


    <div class="form-actions">
      <%= f.submit "Submit", :class => "btn btn-primary" %>
      <%= link_to "Back <i class='icon-arrow-left'></i>".html_safe, :back, :class => "btn btn-inverse" %>
    </div>
<% end %>

app/views/articles/_form.html.erb
<%= simple_form_for [current_user, @article], :html => {:class => 'form-vertical'} do |f| %>
    <%= f.error_notification %>

    <%= f.input :title, :hint => "The title of the article." %>

    <hr>

    <% if @article.photo.file? %>
      <div class="pull-right">
        <h6>Current Image</h6>
        <p><%= image_tag @article.photo.url(:avatar) %></p>
      </div>
    <% end %>
    <%= f.input :photo, :hint => "5MB limit | JPEG/PNG only." %>

    <hr>

    <%= f.input :content, :as => :text, :input_html => {:class => "span6", :rows => 8} %>


    <div class="form-actions">
      <%= f.submit "Submit", :class => "btn btn-primary" %>
      <%= link_to "Back <i class='icon-arrow-left'></i>".html_safe, :back, :class => "btn btn-inverse" %>
    </div>
<% end %>

app/views/articles/edit.html.erb
<%= provide(:title, 'Edit Article') %>
<div class="row">
  <div class="span8 offset2">
    <ul class="breadcrumb">
      <li>
        <%= link_to "Article Dashboard", article_dashboard_url %>
        <span class="divider">/</span>
      </li>
      <li>
        <%= link_to "#{@article.title}", article_path(@article) %>
        <span class="divider">/</span>
      </li>
      <li class="active">Editing <%= @article.title %></li>
    </ul>
    <div class="well">

      <%= render 'edit_form' %>

    </div>
  </div>
</div>

app/views/articles/home.html.erb
<div class="row">
	<div class="span3">
		<%= link_to "<i class='icon-plus'></i> Create New Article".html_safe, new_user_article_path(current_user), :class => "btn btn-large btn-success" %>
		<hr>

		<h5>Easily manage and edit your articles</h5>
		<p>To get started add a new article, and you find article settings in the edit menu!</p>
	</div>
	<div class="span9">
		<table class="table table-striped table-bordered">
		  <thead>
		    <tr>
		      <th width="30%">Title</th>
		      <th width="30%">Short</th>
		      <th width="10%">Rating</th>
		      <th width="30%">Options</th>
		    </tr>
		  </thead>
		  <tbody>
		  	<% @articles.each do |a| %>
		    <tr>
		      <td><%= link_to a.title, a %></td>
		      <td><%= truncate(strip_tags(a.content), :length => 25, :separator => ' ') %></td>
		      <td>
		      	<i class="icon-star"></i>
		      	<i class="icon-star"></i>
		      	<i class="icon-star"></i>
		      	<i class="icon-star-empty"></i>
		      	<i class="icon-star-empty"></i>
		      </td>
		      <td>
		      	<%= link_to "Edit", edit_article_path(a), :class => "btn btn-mini" %> 
		      	<%= link_to "Delete", article_path(a), :class => "btn btn-danger btn-mini", :confirm => "Are you sure you want to delete this article?", :method => :delete %> 
		      </td>
		    </tr>
		    <% end %>

		  </tbody>
		</table>
		<% if @articles.empty? %>
			<div class="alert alert-warning">There are no articles. <%= link_to "Click here", new_user_article_path(current_user) %> to get started. <a class="close" data-dismiss="alert" href="#">×</a></div>
		<% end %>

	</div>
</div>

app/views/articles/new.html.erb
<%= provide(:title, 'New Article') %>
<div class="row">
  <div class="span8 offset2">
    <ul class="breadcrumb">
      <li>
        <%= link_to "Article Dashboard", article_dashboard_url %>
        <span class="divider">/</span>
      </li>
      <li class="active">New Article</li>
    </ul>
    <div class="well">

      <%= render 'form' %>

    </div>
  </div>
</div>

app/views/articles/show.html.erb
<%= provide(:title, 'Reading article..') %>
<div class="row">
  <div class="span12">
    <ul class="breadcrumb">
      <li>
        <%= link_to @artist.artist_name, @artist %>
        <span class="divider">/</span>
      </li>

      <li class="active">Reading <%= @article.title %></li>
    </ul>
  </div>
</div>

<div class="row">
  <div class="span6">
    <div class="well">

      <h2><%= @article.title %></h2>
      <p>
        <%= image_tag @article.photo.url(:small), :class => "pull-right" if @article.photo.file? %>
        <%= @article.content.html_safe %>
      </p>
      <hr>


    </div>
  </div>
  <div class="span6">

    <div class="well" id="comments">
      <h6 class="hb">Comments</h6>
      <%= render "comments/comments" %>
      <h6 class="hb">Write your own comment</h6>
      <%= render "comments/form" %>
    </div>



  </div>
</div>