config/routes.rb
Moz::Application.routes.draw do

  root :to => "pages#home"

  devise_for :users, :controllers => { :registrations => :registrations }
  devise_for :users, :skip => [:sessions]

  as :user do
    get    'signin' => 'devise/sessions#new', :as => :new_user_session
    post   'signin' => 'devise/sessions#create', :as => :user_session
    delete 'signout' => 'devise/sessions#destroy', :as => :destroy_user_session
  end

  resources :users, :only => [:show, :index]

  resources :users do 

    resources :comments

    resources :articles, :shallow => true do 
      resources :comments 
    end

    resources :events, :shallow => true do 
      resources :comments 
    end

    resources :videos, :shallow => true do 
      resources :comments 
    end

    resources :youtubes, :shallow => true do
      resources :comments
    end

    resources :playlists, :shallow => true do
      resources :ptracks
    end

    resources :albums, :shallow => true do
      resources :comments

      resources :songs do
        resources :comments
      end

    end
  end

  match '/music'               => "pages#music"
  match '/about'               => "pages#about"
  match '/team'                => "pages#team"
  match '/micropost-dashboard' => 'microposts#home',        as: 'song_dashboard'
  match '/song-dashboard'      => 'songs#home',             as: 'song_dashboard'
  match '/gallery-dashboard'   => 'galleries#home',         as: 'gallery_dashboard'
  match '/album-dashboard'     => 'albums#home',            as: 'album_dashboard'
  match '/events-dashboard'    => 'events#home',            as: 'events_dashboard'
  match '/video-dashboard'     => 'videos#home',            as: 'video_dashboard'
  match '/article-dashboard'   => 'articles#home',          as: 'article_dashboard'

end

app/models/video.rb
class Video < ActiveRecord::Base

  attr_accessible :about, :title, :year, :file
  
  belongs_to :user
  has_many :comments, as: :commentable
  validates :title,
          presence: true,
          length: {
              minimum: 2, maximum: 40,
              :message => "is too short"
          }
  validates :about,
          presence: true,
          length: {
              minimum: 2, maximum: 250,
              :message => "you have exceded 250 letters"
          }
  validates_numericality_of :year, :only_integer => true, :message => "can only be whole number."

  validates_inclusion_of :year, :in => 1900..2099, :message => "can only be between 1900 and 2099."

  # Friendly URLS
  # -----
  extend FriendlyId
  friendly_id :title, use: :slugged

  has_attached_file :file, :styles => { 
				        :medium => { :geometry => "640x480", :format => 'flv' },
				        :thumb => { :geometry => "200x200#", :format => 'jpg', :time => 10 }
			  	    }
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  load_and_authorize_resource :only => [:new, :create, :edit, :update, :destroy]
  def home
    @user = current_user
    @videos = @user.videos
    @youtube = @user.youtubes
  end
  def index
    @videos = Video.all
  end

  # GET /videos/1
  # GET /videos/1.json
  def show
    @video = Video.find(params[:id])

    @commentable = @video
    @comments = @commentable.comments
    @comment = Comment.new
  end

  # GET /videos/new
  # GET /videos/new.json
  def new
    @user = User.find(params[:user_id])
    @video = @user.videos.build
  end

  # GET /videos/1/edit
  def edit
    @video = Video.find(params[:id])
    @user = User.find(@video.user_id)
  end

  # POST /videos
  # POST /videos.json
  def create
    @user = User.find(params[:user_id])
    @video = @user.videos.build(params[:video])
    if @video.save
      flash[:notice] = "Successfully created video."
      redirect_to video_dashboard_url
    else
      render :action => 'new'
    end
  end

  # PUT /videos/1
  # PUT /videos/1.json
  def update
    @video = Video.find(params[:id])
    if @video.update_attributes(params[:video])
      flash[:notice] = "Successfully updated video."
      redirect_to video_dashboard_url
    else
      render :action => 'edit'
    end
  end

  # DELETE /videos/1
  # DELETE /videos/1.json
  def destroy
    @video = Video.find(params[:id])
    @video.destroy
    flash[:notice] = "Successfully destroyed video."
    redirect_to video_dashboard_url
  end

end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/videos/_edit_form.html.erb
<%= simple_form_for [@video], :html => {:class => 'form-vertical'} do |f| %>
    <%= f.error_notification %>
    <%= f.input :title %>
    <%= f.input :about, :input_html => {:class => "span4", :rows => 4} %>
    <hr>
    <%= f.input :file %>
    <hr>
    <%= f.input :year %>

    <div class="form-actions">
      <%= f.submit "Submit", :class => "btn btn-primary" %>
      <%= link_to "Back <i class='icon-arrow-left'></i>".html_safe, :back, :class => "btn btn-inverse" %>
    </div>
<% end %>

app/views/videos/_form.html.erb
<%= simple_form_for [current_user, @video], :html => {:class => 'form-vertical'} do |f| %>
    <%= f.error_notification %>
    <%= f.input :title %>
    <%= f.input :about, :input_html => {:class => "span4", :rows => 4} %>
    <hr>
    <%= f.input :file %>
    <hr>
    <%= f.input :year %>

    <div class="form-actions">
      <%= f.submit "Submit", :class => "btn btn-primary" %>
      <%= link_to "Back <i class='icon-arrow-left'></i>".html_safe, :back, :class => "btn btn-inverse" %>
    </div>
<% end %>

app/views/videos/edit.html.erb
<%= provide(:title, 'Edit Video') %>
<div class="row">
  <div class="span6 offset3">
    <ul class="breadcrumb">
      <li>
        <%= link_to "Video Dashboard", video_dashboard_url %>
        <span class="divider">/</span>
      </li>


      <li class="active">Edit Video</li>
    </ul>
    <div class="well">
      <%= link_to "Delete Video".html_safe, video_url(@video), :class => "btn btn-danger btn-mini pull-right", :confirm => "Are you sure you want to delete this video?", :method => :delete %>

      <%= render :partial => 'edit_form' %>

    </div>
  </div>
</div>

app/views/videos/home.html.erb
<%= provide(:title, 'Video Dashboard') %>
<div class="row">
  <div class="span3">

    <%= link_to "<i class='icon-upload-alt'></i> Upload New Video".html_safe, new_user_video_path(current_user), :class => "btn btn-large btn-success" %>
    <hr>

    <%= link_to "<i class='icon-plus'></i> Add Video From Youtube".html_safe, new_user_youtube_path(current_user), :class => "btn btn-large btn-info" %>

    <hr>
    <h5>Easily manage and edit your videos</h5>
    <p>To get started add a new video, and you find video settings in the edit menu!</p>

  </div>
  <div class="span9">
    <h2 class="hb">My Videos</h2>
    <ul class="thumbnails">
      <% @videos.each do |video| %>
          <li class="span3">
            <div class="thumbnail">
              <%= image_tag video.file.url(:thumb) %>

              <div class="btn-group">
                <%= link_to "<i class='icon-eye-open'></i> #{video.title}".html_safe, video_path(video), :class => "btn" %>
                <%= link_to "<i class='icon-edit'></i> Edit".html_safe, edit_video_path(video), :class => "btn btn-danger" %>
              </div>
            </div>
          </li>
      <% end %>

    </ul>
    <h2 class="hb">My Youtube Videos</h2>
    <ul class="thumbnails">
      <% @youtube.each do |video| %>
          <li class="span3">
            <div class="thumbnail">

              <div class="btn-group">
                <%= link_to "<i class='icon-eye-open'></i> #{video.title}".html_safe, youtube_path(video), :class => "btn" %>
                <%= link_to "<i class='icon-edit'></i> Edit".html_safe, edit_youtube_path(video), :class => "btn btn-danger" %>
              </div>
            </div>
          </li>
      <% end %>

    </ul>
    <% if @videos.empty? && @youtube.empty? %>
      <div class="alert alert-warning">There are no videos. <%= link_to "Click here", new_user_article_path(current_user) %> to get started. <a class="close" data-dismiss="alert" href="#">×</a></div>
    <% end %>
  </div>
</div>

app/views/videos/index.html.erb
<h1>Listing videos</h1>

<table>
  <tr>
    <th>User</th>
    <th>Title</th>
    <th>Description</th>
    <th>Youtube url</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @videos.each do |video| %>
  <tr>
    <td><%= video.user %></td>
    <td><%= video.title %></td>
    <td><%= video.description %></td>
    <td><%= video.youtube_url %></td>
    <td><%= link_to 'Show', video %></td>
    <td><%= link_to 'Edit', edit_video_path(video) %></td>
    <td><%= link_to 'Destroy', video, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Video', new_video_path %>

app/views/videos/new.html.erb
<%= provide(:title, 'New Video') %>
<div class="row">
  <div class="span6 offset3">
    <ul class="breadcrumb">
      <li>
        <%= link_to "Video Dashboard", video_dashboard_url %>
        <span class="divider">/</span>
      </li>


      <li class="active">New Video</li>
    </ul>
    <div class="well">

      <%= render 'form' %>

    </div>
  </div>
</div>

app/views/videos/show.html.erb
<div class="row">
	<div class="span6">
		<div class="well">
			<h4 class="hb"><%= @video.title %></h4>
			<p><%= @video.about %></p>

			<h6>Uploaded by</h6>
			<p><%= link_to @video.user.username, @video.user %></p>
			<h6>Uploaded at <%= @video.created_at %></h6>
		</div>
	</div>
	<div class="span6">
	    <div class="well" id="comments">
	      <h6 class="hb">Comments</h6>
	      <%= render "comments/comments" %>
	      <h6 class="hb">Write your own comment</h6>
	      <%= render "comments/form" %>
	    </div>


	</div>
</div>