config/routes.rb
Moz::Application.routes.draw do

  root :to => "pages#home"

  devise_for :users, :controllers => { :registrations => :registrations }
  devise_for :users, :skip => [:sessions]

  as :user do
    get    'signin' => 'devise/sessions#new', :as => :new_user_session
    post   'signin' => 'devise/sessions#create', :as => :user_session
    delete 'signout' => 'devise/sessions#destroy', :as => :destroy_user_session
  end

  resources :users, :only => [:show, :index]

  resources :users do 

    resources :comments

    resources :articles, :shallow => true do 
      resources :comments 
    end

    resources :events, :shallow => true do 
      resources :comments 
    end

    resources :videos, :shallow => true do 
      resources :comments 
    end

    resources :youtubes, :shallow => true do
      resources :comments
    end

    resources :playlists, :shallow => true do
      resources :ptracks
    end

    resources :albums, :shallow => true do
      resources :comments

      resources :songs do
        resources :comments
      end

    end
  end

  match '/music'               => "pages#music"
  match '/about'               => "pages#about"
  match '/team'                => "pages#team"
  match '/micropost-dashboard' => 'microposts#home',        as: 'song_dashboard'
  match '/song-dashboard'      => 'songs#home',             as: 'song_dashboard'
  match '/gallery-dashboard'   => 'galleries#home',         as: 'gallery_dashboard'
  match '/album-dashboard'     => 'albums#home',            as: 'album_dashboard'
  match '/events-dashboard'    => 'events#home',            as: 'events_dashboard'
  match '/video-dashboard'     => 'videos#home',            as: 'video_dashboard'
  match '/article-dashboard'   => 'articles#home',          as: 'article_dashboard'

end

app/models/playlist.rb
class Playlist < ActiveRecord::Base
  belongs_to :user
  has_many :ptracks

  # Friendly URLS
  # -----
  extend FriendlyId
  friendly_id :title, use: :slugged
  
  attr_accessible :title
end

app/controllers/playlists_controller.rb
class PlaylistsController < ApplicationController
  # GET /playlists
  # GET /playlists.json
  def index
    @playlists = Playlist.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @playlists }
    end
  end

  # GET /playlists/1
  # GET /playlists/1.json
  def show
    @playlist = Playlist.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @playlist }
    end
  end

  # GET /playlists/new
  # GET /playlists/new.json
  def new
    @playlist = Playlist.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @playlist }
    end
  end

  # GET /playlists/1/edit
  def edit
    @playlist = Playlist.find(params[:id])
  end

  # POST /playlists
  # POST /playlists.json
  def create
    @playlist = Playlist.new(params[:playlist])

    respond_to do |format|
      if @playlist.save
        format.html { redirect_to @playlist, notice: 'Playlist was successfully created.' }
        format.json { render json: @playlist, status: :created, location: @playlist }
      else
        format.html { render action: "new" }
        format.json { render json: @playlist.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /playlists/1
  # PUT /playlists/1.json
  def update
    @playlist = Playlist.find(params[:id])

    respond_to do |format|
      if @playlist.update_attributes(params[:playlist])
        format.html { redirect_to @playlist, notice: 'Playlist was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @playlist.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /playlists/1
  # DELETE /playlists/1.json
  def destroy
    @playlist = Playlist.find(params[:id])
    @playlist.destroy

    respond_to do |format|
      format.html { redirect_to playlists_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/playlists_helper.rb
module PlaylistsHelper
end

app/views/playlists/_form.html.erb
<%= simple_form_for(@playlist) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.association :user %>
    <%= f.input :title %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/playlists/edit.html.erb
<h1>Editing playlist</h1>

<%= render 'form' %>

<%= link_to 'Show', @playlist %> |
<%= link_to 'Back', playlists_path %>

app/views/playlists/index.html.erb
<h1>Listing playlists</h1>

<table>
  <tr>
    <th>User</th>
    <th>Title</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @playlists.each do |playlist| %>
  <tr>
    <td><%= playlist.user %></td>
    <td><%= playlist.title %></td>
    <td><%= link_to 'Show', playlist %></td>
    <td><%= link_to 'Edit', edit_playlist_path(playlist) %></td>
    <td><%= link_to 'Destroy', playlist, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Playlist', new_playlist_path %>

app/views/playlists/new.html.erb
<h1>New playlist</h1>

<%= render 'form' %>

<%= link_to 'Back', playlists_path %>

app/views/playlists/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>User:</b>
  <%= @playlist.user %>
</p>

<p>
  <b>Title:</b>
  <%= @playlist.title %>
</p>


<%= link_to 'Edit', edit_playlist_path(@playlist) %> |
<%= link_to 'Back', playlists_path %>