config/routes.rb
Moz::Application.routes.draw do

  root :to => "pages#home"

  devise_for :users, :controllers => { :registrations => :registrations }
  devise_for :users, :skip => [:sessions]

  as :user do
    get    'signin' => 'devise/sessions#new', :as => :new_user_session
    post   'signin' => 'devise/sessions#create', :as => :user_session
    delete 'signout' => 'devise/sessions#destroy', :as => :destroy_user_session
  end

  resources :users, :only => [:show, :index]

  resources :users do 

    resources :comments

    resources :articles, :shallow => true do 
      resources :comments 
    end

    resources :events, :shallow => true do 
      resources :comments 
    end

    resources :videos, :shallow => true do 
      resources :comments 
    end

    resources :youtubes, :shallow => true do
      resources :comments
    end

    resources :playlists, :shallow => true do
      resources :ptracks
    end

    resources :albums, :shallow => true do
      resources :comments

      resources :songs do
        resources :comments
      end

    end
  end

  match '/music'               => "pages#music"
  match '/about'               => "pages#about"
  match '/team'                => "pages#team"
  match '/micropost-dashboard' => 'microposts#home',        as: 'song_dashboard'
  match '/song-dashboard'      => 'songs#home',             as: 'song_dashboard'
  match '/gallery-dashboard'   => 'galleries#home',         as: 'gallery_dashboard'
  match '/album-dashboard'     => 'albums#home',            as: 'album_dashboard'
  match '/events-dashboard'    => 'events#home',            as: 'events_dashboard'
  match '/video-dashboard'     => 'videos#home',            as: 'video_dashboard'
  match '/article-dashboard'   => 'articles#home',          as: 'article_dashboard'

end

app/models/ptrack.rb
class Ptrack < ActiveRecord::Base
  belongs_to :playlist
  attr_accessible :song_id
end

app/controllers/ptracks_controller.rb
class PtracksController < ApplicationController
  # GET /ptracks
  # GET /ptracks.json
  def index
    @ptracks = Ptrack.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @ptracks }
    end
  end

  # GET /ptracks/1
  # GET /ptracks/1.json
  def show
    @ptrack = Ptrack.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @ptrack }
    end
  end

  # GET /ptracks/new
  # GET /ptracks/new.json
  def new
    @ptrack = Ptrack.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @ptrack }
    end
  end

  # GET /ptracks/1/edit
  def edit
    @ptrack = Ptrack.find(params[:id])
  end

  # POST /ptracks
  # POST /ptracks.json
  def create
    @ptrack = Ptrack.new(params[:ptrack])

    respond_to do |format|
      if @ptrack.save
        format.html { redirect_to @ptrack, notice: 'Ptrack was successfully created.' }
        format.json { render json: @ptrack, status: :created, location: @ptrack }
      else
        format.html { render action: "new" }
        format.json { render json: @ptrack.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /ptracks/1
  # PUT /ptracks/1.json
  def update
    @ptrack = Ptrack.find(params[:id])

    respond_to do |format|
      if @ptrack.update_attributes(params[:ptrack])
        format.html { redirect_to @ptrack, notice: 'Ptrack was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @ptrack.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ptracks/1
  # DELETE /ptracks/1.json
  def destroy
    @ptrack = Ptrack.find(params[:id])
    @ptrack.destroy

    respond_to do |format|
      format.html { redirect_to ptracks_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/ptracks_helper.rb
module PtracksHelper
end

app/views/ptracks/_form.html.erb
<%= simple_form_for(@ptrack) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.association :user %>
    <%= f.input :song_id %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/ptracks/edit.html.erb
<h1>Editing ptrack</h1>

<%= render 'form' %>

<%= link_to 'Show', @ptrack %> |
<%= link_to 'Back', ptracks_path %>

app/views/ptracks/index.html.erb
<h1>Listing ptracks</h1>

<table>
  <tr>
    <th>User</th>
    <th>Song</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @ptracks.each do |ptrack| %>
  <tr>
    <td><%= ptrack.user %></td>
    <td><%= ptrack.song_id %></td>
    <td><%= link_to 'Show', ptrack %></td>
    <td><%= link_to 'Edit', edit_ptrack_path(ptrack) %></td>
    <td><%= link_to 'Destroy', ptrack, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Ptrack', new_ptrack_path %>

app/views/ptracks/new.html.erb
<h1>New ptrack</h1>

<%= render 'form' %>

<%= link_to 'Back', ptracks_path %>

app/views/ptracks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>User:</b>
  <%= @ptrack.user %>
</p>

<p>
  <b>Song:</b>
  <%= @ptrack.song_id %>
</p>


<%= link_to 'Edit', edit_ptrack_path(@ptrack) %> |
<%= link_to 'Back', ptracks_path %>